# ASSIGNMENT_1

In [1]:
#5.	Write a program which accepts a sequence of comma-separated numbers from console and generate a list, tuple 
#and a set which contains every number as per their properties?

In [2]:
sample_set = {10, 20, 30, 40}
l = []
for i in sample_set:
    l.append(i)
print(l)

[40, 10, 20, 30]


In [3]:
values = input("Input some comma seprated numbers : ")
list = values.split(",")
tuple = tuple(list)
print('List : ',list)
print('Tuple : ',tuple)

Input some comma seprated numbers : 45,41,21
List :  ['45', '41', '21']
Tuple :  ('45', '41', '21')


In [5]:
#6.	Create an iterator that returns numbers, starting with 1, and each sequence will increase by one (returning 1,2,3,4,5...) 
#and raise StopIteration exception when the number is greater than 10 ?

In [12]:
class number:
    def __iter__(self):
        self.a = 1
        return self

    def __next__(self):
        if self.a <= 10:
            x = self.a
            self.a += 1
            return x
        else:
            raise StopIteration

myclass = number()
myiter = iter(myclass)

for x in myiter:
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [13]:
#7.	Program to find the sum of first 100 natural numbers using range() ?

In [18]:
sum = 0
for j in range(1,101):
    sum = sum + j
    if j<=99:
        print(sum, end=',')
    else:
        print(sum)

1,3,6,10,15,21,28,36,45,55,66,78,91,105,120,136,153,171,190,210,231,253,276,300,325,351,378,406,435,465,496,528,561,595,630,666,703,741,780,820,861,903,946,990,1035,1081,1128,1176,1225,1275,1326,1378,1431,1485,1540,1596,1653,1711,1770,1830,1891,1953,2016,2080,2145,2211,2278,2346,2415,2485,2556,2628,2701,2775,2850,2926,3003,3081,3160,3240,3321,3403,3486,3570,3655,3741,3828,3916,4005,4095,4186,4278,4371,4465,4560,4656,4753,4851,4950,5050


In [19]:
#8.	Program to create a copy of an object1 to object2 and append new element to object2

In [1]:
import numpy as np
import copy
R = int(input("Enter the number of rows:"))
matrix = []
for k in range(0,R):          
    sab = k+1
    a =[]
    for m in range(3):     
         a.append(sab)
    matrix.append(a)
for k in range(R):
    for m in range(3):
        print(matrix[k][m], end = " ")
    print()
matrix_1 = copy.deepcopy(matrix)
print(k)
k+=2 
matrix = np.array(matrix)
r = np.array([k,k,k])
matrix_1 = np.append(matrix_1,[r],axis= 0)
print(matrix)
print(matrix_1)

Enter the number of rows:3
1 1 1 
2 2 2 
3 3 3 
2
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
