In [17]:
import numpy as np

In [18]:
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
import io

In [20]:
dataset=pd.read_csv('x_final_csv.csv')

In [21]:
dataset

Standard Error  Median  Mode  Standard Deviation  Sample Variance  \
0          0.142599   365.0   366            1.425985         2.033434   
1          0.126027   368.0   368            1.260271         1.588283   
2          0.097333   371.0   371            0.973331         0.947374   
3          0.099372   373.0   373            0.993718         0.987475   
4          0.094554   376.0   376            0.945537         0.894040   
..              ...     ...   ...                 ...              ...   
295        1.069559   325.0   330           10.695586       114.395556   
296        1.131819   324.5   327           11.318190       128.101414   
297        1.137146   316.5   316           11.371464       129.310202   
298        1.971869   344.5   346           19.718688       388.826667   
299        0.961634   347.5   348            3.846535        14.795833   

     Kurtosis  Skewness  Range  Minimum  Maximum    Sum  Count    Condition  
0   -0.897223 -0.105681      6      362      368  36513    100         Good  
1   -0.395387  0.265678      5      366      371  36826    100         Good  
2   -0.400559 -0.177908      4      369      373  37089    100         Good  
3   -0.824843  0.072199      4      371      375  37332    100         Good  
4   -0.187940 -0.205709      5      373      378  37557    100         Good  
..        ...       ...    ...      ...      ...    ...    ...          ...  
295  0.435310 -0.668873     54      290      344  32322    100  Crater wear  
296 -0.008641 -0.555331     53      291      344  32314    100  Crater wear  
297 -0.046520 -0.069875     56      285      341  31677    100  Crater wear  
298 -0.073315 -1.185157     74      283      357  33304    100  Crater wear  
299  2.440078  1.747884     13      345      358   5577     16  Crater wear  

[300 rows x 13 columns]

In [23]:
x=dataset.iloc[:,0:12].values
y=dataset.iloc[:,12].values

In [24]:
y

array(['Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
       'Notch wear', 'Notch wear', 'Notch wear', 'Notch wear',
     

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
encoder=LabelEncoder()

In [27]:
y1=encoder.fit_transform(y)

In [11]:
y2=pd.get_dummies(y1).values

In [12]:
y2

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       ...,
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=uint8)

In [28]:
y1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
log_model=LogisticRegression()

In [31]:
from sklearn.model_selection import  KFold

In [32]:
n_split=5

In [33]:
for train_index,test_index in KFold(n_split).split(x):
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y1[train_index],y1[test_index]
  

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
sc=StandardScaler()

In [36]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [37]:
log_model.fit(x_train,y_train)

LogisticRegression()

In [38]:
y_pred=log_model.predict(x_test)

In [40]:
y_test

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
confusion_matrix(y_test,y_pred)

array([[ 0, 32, 18,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  1,  4,  5]], dtype=int64)